# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 846b03b5c574cf7650a796ac333f52a754461fd94bff2fa802c69d2f4c84a0f08af22ce3788b256457ba4a5dbbba1e10d2d6d6e8c8fcff4e1b34e6b58c77fade

test:
  secret_key_base: 946ca6e797f4fa7bdc999ea4de35c17a7b2a932ddc45df35378685c69ae5779de21a793f2812f91b10c2020e2b597506820aedeb2a5e7cc7d27a257b12826edc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
